### ISSUE TITLE
Fix the helper text with a proper command

### ISSUE THREAD

**Issue by frol** [FroVolod/near-cli#28]
This command does not exist: https://github.com/FroVolod/near-cli/blob/a00ec692cbe56ae21130863af80b1ccfeebbfde7/src/commands/execute_command/change_method/operation_mode/offline_mode/mod.rs#L53

Instead, `near-cli view nonce ...` exists.

![image](https://user-images.githubusercontent.com/304265/123458314-4b11f200-d5bb-11eb-92ed-adc19040670f.png)

**Comment by frol** [comment]
The code is copy-pasted in many places, so it needs to be updated everywhere

**Comment by FroVolod** [comment]
done
