### ISSUE TITLE
`login` keychain error

### ISSUE THREAD

**Issue by khorolets** [FroVolod/near-cli#38]
During the login flow file with credentials is stored in the `~/.near-credentials/testnet/<account>.json`

And when I try to sign transaction with keychain near-cli is trying to find credentials in `~/.near-credentials/default/<account>.json` which causes an error

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: src/commands/construct_transaction_command/sign_transaction/sign_with_keychain/mod.rs:43
```

My near-cli version is near-cli 0.1.0 if it helps.

**Comment by frol** [comment]
@khorolets did you use offline mode? Can you share the flow of the second command?

**Comment by khorolets** [comment]
Online. Any transaction literally

**Comment by frol** [comment]
According to the code line reported on the cash, I believe it was an old version of near-cli as of this commit:

https://github.com/FroVolod/near-cli/blob/e9a900b6f5d48c7c3c53c9cde9b79f3cc1f13172/src/commands/construct_transaction_command/sign_transaction/sign_with_keychain/mod.rs#L43

Newer version should not have this problem.
